### ISSUE TITLE
Need a new share image

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2022#2]
The current one at `/images/og-image-twitter.png` needs to be more polished.

**Comment by si-the-pie** [comment]
![mobileweb_twitter](https://github.com/user-attachments/assets/d389bd7b-09a2-4f7e-92aa-df082d67d93e)

Oh gosh yes it's awful / dreadful, but where is this file used? (I don't remember creating it myself.)

**Comment by mvl22** [comment]
It's picked up automatically by Twitter (and other Open Graph consumers) due to the reference in the document head.

Looks like Patrick created this quick placeholder.

**Comment by mvl22** [comment]
Replaced by the logo SVG in 5e94096d98f40b8ec8fc236596a551fa772e15bb.
