### ISSUE TITLE
Dark Mode - Collisions Pop-Ups

### ISSUE THREAD

**Issue by si-the-pie** [cyclestreets/mobileweb2022#24]
In dark mode the text in the pop-ups of the collisions view is very difficult to see. It appears as light grey on a white background.

## Dark
![dark_mode_collision](https://github.com/user-attachments/assets/5a7d09b0-05bb-41e9-a2f7-8588b3492a72)
## Light
![light_mode_collision](https://github.com/user-attachments/assets/3e0c36fc-36bc-47f9-bd6a-38a9ef8bc82d)

**Comment by mvl22** [comment]
Fixed in 88b6dcf2391fe15b4606f67074e5493426967427; thanks for reporting this.

![Screenshot 2024-11-15 at 00 06 08](https://github.com/user-attachments/assets/da93814c-89d4-4fc7-ac7c-d46c0b52029e)
