### ISSUE TITLE
Photo flip results in unclickable links with reversed text

### ISSUE THREAD

**Issue by mvl22** [cyclestreets/mobileweb2022#4]
The photo flip animation is nice, but the X button at the top is not clickable and the text of the links at the bottom are reversed:

![Screenshot 2020-12-31 at 00 22 13](https://user-images.githubusercontent.com/361423/103387929-61545f00-4afe-11eb-8588-1b5d51d35611.png)

MacOS/Chrome.

**Comment by Siequnu** [comment]
Can't reproduce on MacOS 11.1 with Safari, but could reproduce on Chrome. Attached, Safari 14.0.2 screenshot.
<img width="408" alt="Screenshot 2021-01-06 at 14 25 29" src="https://user-images.githubusercontent.com/11821606/103736372-14efae80-502b-11eb-918e-2fc9a6194463.png">

**Comment by Siequnu** [comment]
It appears that there are 4 elements that bleeding through (Photo info, Share, Get directions and Close popup) have CSS positioning absolute. It would appear that Chrome is still displaying these even though a rotateY transform is being applied to the popup. Both -webkit-backface-visibility and backface-visibility are set in the CSS as hidden.

**Comment by mvl22** [comment]
> rotateY transform

It's possible that the property is being inherited by child elements. If so, they will need to have an override to revert it.

**Comment by mvl22** [comment]
No longer happening on Chrome, so closing this. Probably fixed in browser.
